import {
  ROLE_ACCUEIL,
  ROLE_ADMIN,
  ROLE_APPUI_TNS,
  ROLE_DEMO,
  ROLE_DIRECTION,
  ROLE_GOUVERNANCE_CA,
  ROLE_PROFESSIONNELLE,
  ROLE_RELAIS_LOGEMENT,
} from "./roles";

export const ACCOMPAGNEMENT_ROLES = [
  ROLE_PROFESSIONNELLE,
  ROLE_APPUI_TNS,
  ROLE_ADMIN,
  ROLE_DEMO,
];

export const PARCOURS_ROLES = [ROLE_PROFESSIONNELLE, ROLE_ADMIN, ROLE_DEMO];

export const CONTINUITE_ROLES = [
  ROLE_PROFESSIONNELLE,
  ROLE_APPUI_TNS,
  ROLE_ACCUEIL,
  ROLE_RELAIS_LOGEMENT,
  ROLE_DIRECTION,
  ROLE_ADMIN,
  ROLE_DEMO,
];

export const DIRECTION_ROLES = [ROLE_DIRECTION, ROLE_ADMIN, ROLE_DEMO];
export const GOUVERNANCE_ROLES = [ROLE_GOUVERNANCE_CA, ROLE_ADMIN, ROLE_DEMO];
export const PORTE_DIRECTION_ROLES = [...new Set([...DIRECTION_ROLES, ...GOUVERNANCE_ROLES])];

export function roleIsAllowed(role, allowedRoles) {
  return allowedRoles.includes(role);
}
